//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.8669
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Data;



[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
[System.ServiceModel.ServiceContractAttribute(ConfigurationName = "IRelationalService")]
public interface IRelationalService
{

    // CODEGEN: Parameter 'GetDataResult' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
    [System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/IRelationalService/GetData", ReplyAction = "http://tempuri.org/IRelationalService/GetDataResponse")]
    [System.ServiceModel.XmlSerializerFormatAttribute()]
    GetDataResponse GetData(GetDataRequest request);

    // CODEGEN: Parameter 'GetDataSetInternal1Result' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
    [System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/IRelationalService/GetDataSetInternal1", ReplyAction = "http://tempuri.org/IRelationalService/GetDataSetInternal1Response")]
    [System.ServiceModel.XmlSerializerFormatAttribute()]
    GetDataSetInternal1Response GetDataSetInternal1(GetDataSetInternal1Request request);

    // CODEGEN: Parameter 'GetDataSetInternal2Result' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
    [System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/IRelationalService/GetDataSetInternal2", ReplyAction = "http://tempuri.org/IRelationalService/GetDataSetInternal2Response")]
    [System.ServiceModel.XmlSerializerFormatAttribute()]
    GetDataSetInternal2Response GetDataSetInternal2(GetDataSetInternal2Request request);

    // CODEGEN: Parameter 'GetDataSetInternal3Result' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
    [System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/IRelationalService/GetDataSetInternal3", ReplyAction = "http://tempuri.org/IRelationalService/GetDataSetInternal3Response")]
    [System.ServiceModel.XmlSerializerFormatAttribute()]
    GetDataSetInternal3Response GetDataSetInternal3(GetDataSetInternal3Request request);

    // CODEGEN: Parameter 'GetReportDataPagedResult' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
    [System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/IRelationalService/GetReportDataPaged", ReplyAction = "http://tempuri.org/IRelationalService/GetReportDataPagedResponse")]
    [System.ServiceModel.XmlSerializerFormatAttribute()]
    GetReportDataPagedResponse GetReportDataPaged(GetReportDataPagedRequest request);

    // CODEGEN: Parameter 'GetDataSetListResult' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
    [System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/IRelationalService/GetDataSetList", ReplyAction = "http://tempuri.org/IRelationalService/GetDataSetListResponse")]
    [System.ServiceModel.XmlSerializerFormatAttribute()]
    GetDataSetListResponse GetDataSetList(GetDataSetListRequest request);
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
[System.ServiceModel.MessageContractAttribute(WrapperName = "GetData", WrapperNamespace = "http://tempuri.org/", IsWrapped = true)]
public partial class GetDataRequest
{

    [System.ServiceModel.MessageBodyMemberAttribute(Namespace = "http://tempuri.org/", Order = 0)]
    public int value;

    public GetDataRequest()
    {
    }

    public GetDataRequest(int value)
    {
        this.value = value;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
[System.ServiceModel.MessageContractAttribute(WrapperName = "GetDataResponse", WrapperNamespace = "http://tempuri.org/", IsWrapped = true)]
public partial class GetDataResponse
{

    [System.ServiceModel.MessageBodyMemberAttribute(Namespace = "http://tempuri.org/", Order = 0)]
    [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
    public string GetDataResult;

    public GetDataResponse()
    {
    }

    public GetDataResponse(string GetDataResult)
    {
        this.GetDataResult = GetDataResult;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
[System.ServiceModel.MessageContractAttribute(WrapperName = "GetDataSetInternal1", WrapperNamespace = "http://tempuri.org/", IsWrapped = true)]
public partial class GetDataSetInternal1Request
{

    [System.ServiceModel.MessageBodyMemberAttribute(Namespace = "http://tempuri.org/", Order = 0)]
    [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
    public string sql;

    [System.ServiceModel.MessageBodyMemberAttribute(Namespace = "http://tempuri.org/", Order = 1)]
    [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
    public string Connect;

    public GetDataSetInternal1Request()
    {
    }

    public GetDataSetInternal1Request(string sql, string Connect)
    {
        this.sql = sql;
        this.Connect = Connect;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
[System.ServiceModel.MessageContractAttribute(WrapperName = "GetDataSetInternal1Response", WrapperNamespace = "http://tempuri.org/", IsWrapped = true)]
public partial class GetDataSetInternal1Response
{

    [System.ServiceModel.MessageBodyMemberAttribute(Namespace = "http://tempuri.org/", Order = 0)]
    [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
    public System.Data.DataSet GetDataSetInternal1Result;

    public GetDataSetInternal1Response()
    {
    }

    public GetDataSetInternal1Response(System.Data.DataSet GetDataSetInternal1Result)
    {
        this.GetDataSetInternal1Result = GetDataSetInternal1Result;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
[System.ServiceModel.MessageContractAttribute(WrapperName = "GetDataSetInternal2", WrapperNamespace = "http://tempuri.org/", IsWrapped = true)]
public partial class GetDataSetInternal2Request
{

    [System.ServiceModel.MessageBodyMemberAttribute(Namespace = "http://tempuri.org/", Order = 0)]
    [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
    public string sql;

    [System.ServiceModel.MessageBodyMemberAttribute(Namespace = "http://tempuri.org/", Order = 1)]
    [System.Xml.Serialization.XmlArrayAttribute(IsNullable = true)]
    [System.Xml.Serialization.XmlArrayItemAttribute(Namespace = "http://schemas.microsoft.com/2003/10/Serialization/Arrays")]
    public string[] sqlPar;

    [System.ServiceModel.MessageBodyMemberAttribute(Namespace = "http://tempuri.org/", Order = 2)]
    [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
    public string Connect;

    public GetDataSetInternal2Request()
    {
    }

    public GetDataSetInternal2Request(string sql, string[] sqlPar, string Connect)
    {
        this.sql = sql;
        this.sqlPar = sqlPar;
        this.Connect = Connect;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
[System.ServiceModel.MessageContractAttribute(WrapperName = "GetDataSetInternal2Response", WrapperNamespace = "http://tempuri.org/", IsWrapped = true)]
public partial class GetDataSetInternal2Response
{

    [System.ServiceModel.MessageBodyMemberAttribute(Namespace = "http://tempuri.org/", Order = 0)]
    [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
    public System.Data.DataSet GetDataSetInternal2Result;

    public GetDataSetInternal2Response()
    {
    }

    public GetDataSetInternal2Response(System.Data.DataSet GetDataSetInternal2Result)
    {
        this.GetDataSetInternal2Result = GetDataSetInternal2Result;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
[System.ServiceModel.MessageContractAttribute(WrapperName = "GetDataSetInternal3", WrapperNamespace = "http://tempuri.org/", IsWrapped = true)]
public partial class GetDataSetInternal3Request
{

    [System.ServiceModel.MessageBodyMemberAttribute(Namespace = "http://tempuri.org/", Order = 0)]
    [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
    public string sql;

    [System.ServiceModel.MessageBodyMemberAttribute(Namespace = "http://tempuri.org/", Order = 1)]
    [System.Xml.Serialization.XmlArrayAttribute(IsNullable = true)]
    [System.Xml.Serialization.XmlArrayItemAttribute("ArrayOfstring", Namespace = "http://schemas.microsoft.com/2003/10/Serialization/Arrays")]
    [System.Xml.Serialization.XmlArrayItemAttribute(Namespace = "http://schemas.microsoft.com/2003/10/Serialization/Arrays", NestingLevel = 1)]
    public string[][] listParameters;

    [System.ServiceModel.MessageBodyMemberAttribute(Namespace = "http://tempuri.org/", Order = 2)]
    [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
    public string Connect;

    public GetDataSetInternal3Request()
    {
    }

    public GetDataSetInternal3Request(string sql, string[][] listParameters, string Connect)
    {
        this.sql = sql;
        this.listParameters = listParameters;
        this.Connect = Connect;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
[System.ServiceModel.MessageContractAttribute(WrapperName = "GetDataSetInternal3Response", WrapperNamespace = "http://tempuri.org/", IsWrapped = true)]
public partial class GetDataSetInternal3Response
{

    [System.ServiceModel.MessageBodyMemberAttribute(Namespace = "http://tempuri.org/", Order = 0)]
    [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
    public System.Data.DataSet GetDataSetInternal3Result;

    public GetDataSetInternal3Response()
    {
    }

    public GetDataSetInternal3Response(System.Data.DataSet GetDataSetInternal3Result)
    {
        this.GetDataSetInternal3Result = GetDataSetInternal3Result;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
[System.ServiceModel.MessageContractAttribute(WrapperName = "GetReportDataPaged", WrapperNamespace = "http://tempuri.org/", IsWrapped = true)]
public partial class GetReportDataPagedRequest
{

    [System.ServiceModel.MessageBodyMemberAttribute(Namespace = "http://tempuri.org/", Order = 0)]
    [System.Xml.Serialization.XmlArrayAttribute(IsNullable = true)]
    [System.Xml.Serialization.XmlArrayItemAttribute("ArrayOfstring", Namespace = "http://schemas.microsoft.com/2003/10/Serialization/Arrays")]
    [System.Xml.Serialization.XmlArrayItemAttribute(Namespace = "http://schemas.microsoft.com/2003/10/Serialization/Arrays", NestingLevel = 1)]
    public string[][] relReport;

    [System.ServiceModel.MessageBodyMemberAttribute(Namespace = "http://tempuri.org/", Order = 1)]
    public int from;

    [System.ServiceModel.MessageBodyMemberAttribute(Namespace = "http://tempuri.org/", Order = 2)]
    public int to;

    [System.ServiceModel.MessageBodyMemberAttribute(Namespace = "http://tempuri.org/", Order = 3)]
    [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
    public string Connect;

    public GetReportDataPagedRequest()
    {
    }

    public GetReportDataPagedRequest(string[][] relReport, int from, int to, string Connect)
    {
        this.relReport = relReport;
        this.from = from;
        this.to = to;
        this.Connect = Connect;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
[System.ServiceModel.MessageContractAttribute(WrapperName = "GetReportDataPagedResponse", WrapperNamespace = "http://tempuri.org/", IsWrapped = true)]
public partial class GetReportDataPagedResponse
{

    [System.ServiceModel.MessageBodyMemberAttribute(Namespace = "http://tempuri.org/", Order = 0)]
    [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
    public System.Data.DataSet GetReportDataPagedResult;

    public GetReportDataPagedResponse()
    {
    }

    public GetReportDataPagedResponse(System.Data.DataSet GetReportDataPagedResult)
    {
        this.GetReportDataPagedResult = GetReportDataPagedResult;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
[System.ServiceModel.MessageContractAttribute(WrapperName = "GetDataSetList", WrapperNamespace = "http://tempuri.org/", IsWrapped = true)]
public partial class GetDataSetListRequest
{

    [System.ServiceModel.MessageBodyMemberAttribute(Namespace = "http://tempuri.org/", Order = 0)]
    [System.Xml.Serialization.XmlArrayAttribute(IsNullable = true)]
    [System.Xml.Serialization.XmlArrayItemAttribute("ArrayOfstring", Namespace = "http://schemas.microsoft.com/2003/10/Serialization/Arrays")]
    [System.Xml.Serialization.XmlArrayItemAttribute(Namespace = "http://schemas.microsoft.com/2003/10/Serialization/Arrays", NestingLevel = 1)]
    public string[][] sqlParList;

    public GetDataSetListRequest()
    {
    }

    public GetDataSetListRequest(string[][] sqlParList)
    {
        this.sqlParList = sqlParList;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
[System.ServiceModel.MessageContractAttribute(WrapperName = "GetDataSetListResponse", WrapperNamespace = "http://tempuri.org/", IsWrapped = true)]
public partial class GetDataSetListResponse
{

    [System.ServiceModel.MessageBodyMemberAttribute(Namespace = "http://tempuri.org/", Order = 0)]
    [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
    public System.Data.DataSet GetDataSetListResult;

    public GetDataSetListResponse()
    {
    }

    public GetDataSetListResponse(System.Data.DataSet GetDataSetListResult)
    {
        this.GetDataSetListResult = GetDataSetListResult;
    }
}

[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
public interface IRelationalServiceChannel : IRelationalService, System.ServiceModel.IClientChannel
{
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
public partial class RelationalServiceClient : System.ServiceModel.ClientBase<IRelationalService>, IRelationalService
{

    public RelationalServiceClient()
    {
    }

    public RelationalServiceClient(string endpointConfigurationName) :
        base(endpointConfigurationName)
    {
    }

    public RelationalServiceClient(string endpointConfigurationName, string remoteAddress) :
        base(endpointConfigurationName, remoteAddress)
    {
    }

    public RelationalServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) :
        base(endpointConfigurationName, remoteAddress)
    {
    }

    public RelationalServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) :
        base(binding, remoteAddress)
    {
    }

    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    GetDataResponse IRelationalService.GetData(GetDataRequest request)
    {
        return base.Channel.GetData(request);
    }

    public string GetData(int value)
    {
        GetDataRequest inValue = new GetDataRequest();
        inValue.value = value;
        GetDataResponse retVal = ((IRelationalService)(this)).GetData(inValue);
        return retVal.GetDataResult;
    }

    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    GetDataSetInternal1Response IRelationalService.GetDataSetInternal1(GetDataSetInternal1Request request)
    {
        return base.Channel.GetDataSetInternal1(request);
    }

    public System.Data.DataSet GetDataSetInternal1(string sql, string Connect)
    {
        GetDataSetInternal1Request inValue = new GetDataSetInternal1Request();
        inValue.sql = sql;
        inValue.Connect = Connect;
        GetDataSetInternal1Response retVal = ((IRelationalService)(this)).GetDataSetInternal1(inValue);
        return retVal.GetDataSetInternal1Result;
    }

    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    GetDataSetInternal2Response IRelationalService.GetDataSetInternal2(GetDataSetInternal2Request request)
    {
        return base.Channel.GetDataSetInternal2(request);
    }

    public System.Data.DataSet GetDataSetInternal2(string sql, string[] sqlPar, string Connect)
    {
        GetDataSetInternal2Request inValue = new GetDataSetInternal2Request();
        inValue.sql = sql;
        inValue.sqlPar = sqlPar;
        inValue.Connect = Connect;
        GetDataSetInternal2Response retVal = ((IRelationalService)(this)).GetDataSetInternal2(inValue);
        return retVal.GetDataSetInternal2Result;
    }

    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    GetDataSetInternal3Response IRelationalService.GetDataSetInternal3(GetDataSetInternal3Request request)
    {
        return base.Channel.GetDataSetInternal3(request);
    }

    public System.Data.DataSet GetDataSetInternal3(string sql, string[][] listParameters, string Connect)
    {
        GetDataSetInternal3Request inValue = new GetDataSetInternal3Request();
        inValue.sql = sql;
        inValue.listParameters = listParameters;
        inValue.Connect = Connect;
        GetDataSetInternal3Response retVal = ((IRelationalService)(this)).GetDataSetInternal3(inValue);
        return retVal.GetDataSetInternal3Result;
    }

    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    GetReportDataPagedResponse IRelationalService.GetReportDataPaged(GetReportDataPagedRequest request)
    {
        return base.Channel.GetReportDataPaged(request);
    }

    public System.Data.DataSet GetReportDataPaged(string[][] relReport, int from, int to, string Connect)
    {
        GetReportDataPagedRequest inValue = new GetReportDataPagedRequest();
        inValue.relReport = relReport;
        inValue.from = from;
        inValue.to = to;
        inValue.Connect = Connect;
        GetReportDataPagedResponse retVal = ((IRelationalService)(this)).GetReportDataPaged(inValue);
        return retVal.GetReportDataPagedResult;
    }

    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    GetDataSetListResponse IRelationalService.GetDataSetList(GetDataSetListRequest request)
    {
        return base.Channel.GetDataSetList(request);
    }

    public System.Data.DataSet GetDataSetList(string[][] sqlParList)
    {
        GetDataSetListRequest inValue = new GetDataSetListRequest();
        inValue.sqlParList = sqlParList;
        GetDataSetListResponse retVal = ((IRelationalService)(this)).GetDataSetList(inValue);
        return retVal.GetDataSetListResult;
    }
}
